name: build-docs

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Conda
      uses: conda-incubator/setup-miniconda@v2.1.1
      with:
        activate-environment: clouddrift
        environment-file: environment.yml
        mamba-version: "*"
        channels: conda-forge,defaults
        channel-priority: true
    - name: Build docs
      uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "docs/"
    - name: Upload HTML artificat
      uses: actions/upload-artifact@v1
      with:
        name: DocumentationHTML
        path: docs/_build/html/
    - name: Running the Sphinx to gh-pages Action
        uses: uibcdf/action-sphinx-docs-to-gh-pages@v1.0-beta.2
          with:
            branch: main
            dir_docs: docs
            sphinxopts: ''
