name: build-docs

on:
  push:
    branches:
      - main

jobs:
  docs:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.9"]
    defaults:
      run:
        shell: bash -l {0}

    steps:
    - uses: actions/checkout@v3
    - name: Conda
      uses: conda-incubator/setup-miniconda@v2.1.1
      with:
        activate-environment: clouddrift
        environment-file: environment.yml
        mamba-version: "*"
        channels: conda-forge,defaults
        channel-priority: true

    - name: Build docs
      shell: bash -l {0}
      run: |
        pushd docs
        make html
    - name: Upload HTML artificat
      uses: actions/upload-artifact@v3
      with:
        name: DocumentationHTML
        path: docs/_build/html/
    - name: Commit changes
      run: |
        git clone https://github.com/ammaraskar/sphinx-action-test.git --branch gh-pages --single-branch gh-pages
        cp -r docs/_build/html/* gh-pages/
        cd gh-pages
        touch .nojekyll
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Update documentation" -a || true
        # The above command will fail if no changes were present, so we ignore
        # that.
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: gh-pages
        directory: gh-pages
        force: true
